# in the templates via {{ site.myvariable }}.
name                : Red Canari
title               : Red Canari - Home
email               : info@redcanari.com
address             : '2216 Park Avenue, California 95630 '
phone               :  '+1 778 1337 9000'
 
tagline             : ' description for your new site here' 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl             : "" # the subpath of your site, e.g. /blog
url                 : "http://127.0.0.1:4000" #   the base hostname & protocol for your site, e.g. http://example.com
twitter_username    : jekyllrb
github_username     :  jekyll

logo: 'assets/images/logo.png'
favicon: 'assets/images/fav.png'

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /:year/:month/:day/:title:output_ext


plugins:
  - jekyll-feed
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

####################################
######  banner Section   ######
####################################
banner_title: '<span>Advance </span> Your Organizations Resiliency'
banner_description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam for humanity for savings anything for your future.'
banner_image: 'assets/images/banner/1.png'
banner_btn_one_text: 'TALK TO AN EXPERT'
banner_btn_one_link: '#contact'
banner_btn_two_text: ''
banner_btn_two_link: ''

 
#####################################
###########    Teams     ############
#####################################

team_title: Connect With Us
 

teams:

  - name: 'Tony Kanjirappally '
    title: 'Managing Partner, CEO'
    image: 'assets/images/team/tony.jpg'
    linkedin: 'https://www.linkedin.com/in/tonykanjirappally/'
 

  - name: 'Nadeem Douba'
    title: 'Managing Partner, CTO'
    image: 'assets/images/team/naedm.jpg'
    linkedin: 'https://www.linkedin.com/in/nadeem-douba/'
 

  - name: David Mussington 
    title: Cyber Risk Director
    image: 'assets/images/team/david.jpg'
    linkedin: 'https://www.linkedin.com/in/davidmussington'
 

  - name: Dan Lesage
    title: Engineering Director
    image: 'assets/images/team/dan.jpg'
    linkedin: 'https://www.linkedin.com/in/danlesage/ '
 

  - name: Philip Elsas 
    title: Assurance & Audit Director
    image: 'assets/images/team/philip.jpg'
    linkedin: 'https://www.linkedin.com/in/philipelsas/'
 

  - name: Delon Young 
    title: Sales Director
    image: 'assets/images/team/delon.jpg'
    linkedin: 'https://www.linkedin.com/in/delon-young/'
 
  - name: Ahmed Shah 
    title: Director, Security R&D
    image: 'assets/images/team/amed.jpg'
    linkedin: 'https://www.linkedin.com/in/ahmedshahbeng'
    

  - name: Philip George
    title: Director, Corporate Development
    image: 'assets/images/team/PhilipGeorge.jpg'
    linkedin: 'https://www.linkedin.com/in/philip-george-840a643/'
 

  - name: Andrew Fisk
    title: Executive Advisor, GRC
    image: 'assets/images/team/Andrew.jpg'
    linkedin: 'https://www.linkedin.com/in/andrew-fisk-cyber-security-advisor/'
 

  - name: Chris Summer
    title: Executive Advisor, GRC
    image: 'assets/images/team/Chris.jpg'
    linkedin: '#'
 

  - name: Rutvik Gajjar
    title: Security Analyst
    image: 'assets/images/team/rutvik.jpg'
    linkedin: 'https://www.linkedin.com/in/rutvikbgajjar/'
  

  - name: Harsimran Kanwar
    title: Security Analyst
    image: 'assets/images/team/Harsimran.jpg'
    linkedin: 'https://www.linkedin.com/in/harsimran-kanwar-a15338186/'
 

  - name: Arushi Gautam
    title: Administrative Associate
    image: 'assets/images/team/arushi.jpg'
    linkedin: 'https://www.linkedin.com/in/arushi-gautam-1171b0157/'
 

 
####################################
######   Contact  section     ######
####################################
contact_title: 'Contact Us'
contact_description: 'Contact Us For <br> More Information'


 

####################################
######  Global Social Links   ######
####################################
socials: 
  - name: 'twitter'
    url: '#'

  - name: 'facebook'
    url: '#'

  - name: 'linkedin'
    url: '#'

  - name: 'pinterest'
    url: '#'

  - name: 'instagram'
    url: '#'




# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook                 :
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache


 

 


